[workspace]
authors = ["Edoardo Marcora <edoardo.marcora@gmail.com>"]
channels = ["conda-forge"]
name = "playing_with_a_pangolin"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.4,<3.15"
ipython = ">=9.12.0,<10"
seaborn = ">=0.13.2,<0.14"
jupyter = ">=1.1.1,<2"
arviz = ">=1.0.0,<2"
marimo = ">=0.23.1,<0.24"
openai = ">=2.32.0,<3"
python-lsp-server = ">=1.14.0,<2"

[pypi-dependencies]
pangolin = { git = "https://github.com/justindomke/pangolin.git" }
